"""Health report router — generate, list, and view AI health reports.

Endpoints:
  POST /reports/generate          — Trigger report generation
  GET  /reports/{user_id}         — List all reports for a user
  GET  /reports/{user_id}/{report_id} — Get single report detail
  GET  /reports/medical/{user_id} — Get analyzed medical reports (images)
"""

import uuid
from typing import Optional
from fastapi import APIRouter, HTTPException

from app.config import session_service
from app.schemas.report import GenerateReportRequest

router = APIRouter(prefix="/reports", tags=["Health Reports"])


@router.post("/generate")
async def generate_report_endpoint(request: GenerateReportRequest):
    """Generate a health report (daily, weekly, monthly, or emergency).

    The report is generated by the standalone Report Agent using
    aggregated health data from conversations, medical reports,
    and user profile.

    Can be triggered by:
      - Elder manually requesting a report
      - Caregiver requesting a report for their elder
      - Backend cron job for scheduled reports
      - Emergency system on SOS trigger

    Args:
        request: Report generation parameters including user_id, report_type,
                 and optional date range overrides.

    Returns:
        Generated report with report_id and full content.
    """
    # Validate report type
    valid_types = {"daily", "weekly", "monthly", "emergency"}
    if request.report_type not in valid_types:
        raise HTTPException(
            status_code=400,
            detail=f"Invalid report_type. Must be one of: {', '.join(valid_types)}",
        )

    from seniocare.tools.reports import generate_report

    try:
        result = await generate_report(
            user_id=request.user_id,
            report_type=request.report_type,
            start_date=request.start_date,
            end_date=request.end_date,
        )

        # Send FCM notification to caregivers if requested
        notification_result = None
        if request.notify_caregiver:
            notification_result = await _notify_caregivers_for_report(
                user_id=request.user_id,
                report_type=request.report_type,
                report_id=result.get("report_id", ""),
                title=result.get("title", ""),
            )

        return {
            "success": True,
            **result,
            "notification": notification_result,
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Report generation failed: {str(e)}",
        )


async def _notify_caregivers_for_report(
    user_id: str,
    report_type: str,
    report_id: str,
    title: str,
) -> Optional[dict]:
    """Look up caregivers from session state and send FCM notification.

    Args:
        user_id: The elder's user_id.
        report_type: Type of report generated.
        report_id: The generated report's ID.
        title: The report title for the notification.

    Returns:
        Notification result dict or None if no caregivers found.
    """
    try:
        from app.notifications import notify_caregivers

        # Read caregiver data from the elder's session state
        temp_session_id = f"_notif_{uuid.uuid4().hex[:8]}"
        session = await session_service.create_session(
            app_name="seniocare",
            user_id=user_id,
            session_id=temp_session_id,
        )

        caregivers = session.state.get("user:caregivers", []) or []
        elder_name = session.state.get("user:user_name", "المستخدم")

        await session_service.delete_session(
            app_name="seniocare",
            user_id=user_id,
            session_id=temp_session_id,
        )

        if not caregivers:
            print(f"[Reports] No caregivers registered for {user_id} — skipping notification")
            return {"sent": 0, "failed": 0, "details": ["no_caregivers_registered"]}

        # Send FCM push notifications
        result = await notify_caregivers(
            caregivers=caregivers,
            elder_name=elder_name,
            report_type=report_type,
            report_id=report_id,
            elder_user_id=user_id,
        )

        return result

    except Exception as e:
        print(f"[Reports] Caregiver notification failed: {e}")
        return {"sent": 0, "failed": 0, "details": [str(e)]}


@router.get("/{user_id}")
async def list_reports(
    user_id: str,
    report_type: Optional[str] = None,
    limit: int = 20,
):
    """List all health reports for a user.

    Args:
        user_id: The user's identifier.
        report_type: Optional filter ('daily', 'weekly', 'monthly', 'emergency').
        limit: Maximum number of reports to return (default 20).

    Returns:
        List of report summaries ordered by generation date (most recent first).
    """
    from seniocare.tools.reports import get_health_reports

    reports = get_health_reports(
        user_id=user_id,
        report_type=report_type,
        limit=limit,
    )

    return {
        "success": True,
        "user_id": user_id,
        "count": len(reports),
        "reports": reports,
    }


@router.get("/{user_id}/{report_id}")
async def get_report_detail(user_id: str, report_id: str):
    """Get full details of a specific health report.

    Args:
        user_id: The user's identifier (for validation).
        report_id: The report's identifier.

    Returns:
        Full report content with all sections and recommendations.
    """
    from seniocare.tools.reports import get_health_report_detail

    report = get_health_report_detail(report_id)

    if not report:
        raise HTTPException(status_code=404, detail="Report not found")

    if report.get("user_id") != user_id:
        raise HTTPException(status_code=403, detail="Access denied")

    return {
        "success": True,
        "report": report,
    }


@router.get("/medical/{user_id}")
async def get_medical_reports(user_id: str):
    """Retrieve all analyzed medical reports (from image analysis) for a user.

    This endpoint returns reports from the medical_reports table,
    which stores results from medical report image analysis.

    Args:
        user_id: The user's identifier.

    Returns:
        List of analyzed medical report records.
    """
    from seniocare.tools.image_tools import get_user_medical_reports

    reports = get_user_medical_reports(user_id)

    return {
        "success": True,
        "user_id": user_id,
        "count": len(reports),
        "reports": reports,
    }
